name: Benchmarks

on:
  push:
    branches:
      - master
    tags:
      - benchmark-**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .[asgi-file-uploads,tracing,test,dev]
    - name: Benchmark
      run: |
        pytest benchmark --benchmark-storage=file://benchmark/results --benchmark-autosave
        cd benchmark && python rotate_results.py "${{ matrix.python-version }}"
    - name: Commit
      run: |
        git config user.name "pytest-benchmark"
        git config user.email "<>"
        git add benchmark/results --all
        git commit -m "Benchmark results for ${{ matrix.python-version }}"
        git push
